language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "3.7-dev" # 3.7 development branch
  - "3.8"
  - "3.8-dev"
  - "3.9-dev"
# command to install dependencies
install: "pip install lxml"
# command to run tests
script: py.test pymods/tests/tests.py
notifications:
    email: 
        on_success: change
        on_failure: change
